### ISSUE TITLE
Workshop Butler API: Request failed

### ISSUE THREAD

**Issue by iFacilitate** [workshopbutler/wordpress-plugin#29]
I get this error on my Wordpress page. Nothing was changed and the SSL is up and running and also not changed.

Workshop Butler API: Request failed
Reason : cURL error 60: SSL certificate problem: certificate has expired

It seems the error is not in the SSL or Wordpress

**Comment by overlogic** [comment]
Most probably, you are using an old OpenSSL library with outdated root certificates. You can find more details in this article https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ from the certificate authority.
